# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Final_version_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Start_window(object):
    def setupUi(self, Start_window):
        Start_window.setObjectName("Start_window")
        Start_window.resize(830, 500)
        Start_window.setMinimumSize(QtCore.QSize(830, 500))
        Start_window.setMaximumSize(QtCore.QSize(830, 500))
        Start_window.setAutoFillBackground(False)
        Start_window.setStyleSheet("QWidget#centralwidget{\n"
"background-color: qlineargradient(spread:pad, x1:0.136, y1:0.125, x2:0.847458, y2:0.807, stop:0 rgba(177, 222, 249, 255), stop:1 rgba(220, 255, 197, 255));}")
        self.centralwidget = QtWidgets.QWidget(Start_window)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_count_capital_0 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_count_capital_0.setGeometry(QtCore.QRect(30, 130, 765, 80))
        self.btn_count_capital_0.setMinimumSize(QtCore.QSize(0, 80))
        self.btn_count_capital_0.setMaximumSize(QtCore.QSize(16777215, 80))
        font = QtGui.QFont()
        font.setFamily("Miriam CLM")
        font.setPointSize(12)
        self.btn_count_capital_0.setFont(font)
        self.btn_count_capital_0.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_count_capital_0.setStyleSheet("border-radius:20px;\n"
"background-color: rgb(228, 255, 252);")
        self.btn_count_capital_0.setObjectName("btn_count_capital_0")
        self.btn_interest_compon = QtWidgets.QPushButton(self.centralwidget)
        self.btn_interest_compon.setGeometry(QtCore.QRect(30, 230, 765, 80))
        self.btn_interest_compon.setMinimumSize(QtCore.QSize(0, 80))
        self.btn_interest_compon.setSizeIncrement(QtCore.QSize(0, 80))
        font = QtGui.QFont()
        font.setFamily("Miriam CLM")
        font.setPointSize(12)
        self.btn_interest_compon.setFont(font)
        self.btn_interest_compon.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_interest_compon.setStyleSheet("border-radius:20px;\n"
"background-color: rgb(228, 255, 252);")
        self.btn_interest_compon.setObjectName("btn_interest_compon")
        self.btn_capital_future_0 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_capital_future_0.setGeometry(QtCore.QRect(30, 340, 765, 80))
        self.btn_capital_future_0.setMinimumSize(QtCore.QSize(0, 80))
        self.btn_capital_future_0.setSizeIncrement(QtCore.QSize(0, 80))
        font = QtGui.QFont()
        font.setFamily("Miriam CLM")
        font.setPointSize(12)
        self.btn_capital_future_0.setFont(font)
        self.btn_capital_future_0.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_capital_future_0.setStyleSheet("border-radius:20px;\n"
"background-color: rgb(228, 255, 252);")
        self.btn_capital_future_0.setObjectName("btn_capital_future_0")
        self.L_your_helper = QtWidgets.QLabel(self.centralwidget)
        self.L_your_helper.setGeometry(QtCore.QRect(210, 40, 511, 41))
        self.L_your_helper.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.L_your_helper.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";")
        self.L_your_helper.setObjectName("L_your_helper")
        Start_window.setCentralWidget(self.centralwidget)

        self.retranslateUi(Start_window)
        QtCore.QMetaObject.connectSlotsByName(Start_window)

    def retranslateUi(self, Start_window):
        _translate = QtCore.QCoreApplication.translate
        Start_window.setWindowTitle(_translate("Start_window", "Главное окно"))
        self.btn_count_capital_0.setText(_translate("Start_window", "Рассчитать сумму капитала (или пассивного дохода в месяц), через \"n\" лет.\n"
"(Указав размер капитала на конец последних двух лет)"))
        self.btn_interest_compon.setText(_translate("Start_window", "Калькулятор сложных процентов с капитализацией и пополнением.\n"
"(При расчете учитавыются НДФЛ)"))
        self.btn_capital_future_0.setText(_translate("Start_window", "Расчитать сколько лет понадобится, для создания \"n\" капитала."))
        self.L_your_helper.setText(_translate("Start_window", "ВАШ ПОМОЩНИК В ИНВЕСТИЦИЯХ."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Start_window = QtWidgets.QMainWindow()
    start = Ui_Start_window()
    start.setupUi(Start_window)
    Start_window.show()
    sys.exit(app.exec_())
